name: CI Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"  # Puedes usar la versión 16 o la que sea más adecuada
      - name: Install dependencies
        run: npm install  # Asegúrate de que se instalen todas las dependencias correctamente
      - name: Change file permissions for ESLint
        run: chmod +x node_modules/.bin/eslint  # Ajusta los permisos de ESLint
      - name: Run ESLint
        run: npx eslint .  # Ejecuta ESLint en el proyecto

  test:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
